#!/bin/bash

host=`uname -n`

rank=$OMPI_COMM_WORLD_RANK
suffix=`printf "%3.3d" $rank`

export OMP_NUM_THREADS=chk.nt

ulimit -s unlimited

#export KMP_BLOCKTIME=10000
#export KMP_LIBRARY=turnaround
#export KMP_AFFINITY="verbose,granularity=thread,scatter"
#export KMP_AFFINITY="verbose,compact"
#export KMP_MONITOR_STACKSIZE=100m
# これがないと落ちる
#export KMP_STACKSIZE=8000m
export KMP_STACKSIZE=250m

./chk.lm inp/chk.in 1> log.$suffix 2> err.$suffix
