! format
!> @brief Define output format

! #################
! ###  .rep     ###
! #################
! table of replica valiable and label
#define _STR_REP_TABLE_TITLE_  '# Table of replica valiable and label'
#define _FMT_REP_TABLE_LABEL_  '(i5,1x)'
#define _FMT_REP_TABLE_VALUE_  '(f12.4,1x)'
#define _FMT_REP_TABLE_STEP_   '(i12,1x)'
! trajectory
#define _FMT_REP_TRAJ_STEP_    '(i10,1x)'
#define _FMT_REP_TRAJ_R2L_A_   '(i5,1x)'
#define _FMT_REP_TRAJ_R2L_L_   '(i5)'

! #################
! ###  .psf     ###
! #################
! Table of replica valiable and label
#define _STR_PSF_ATOM_RNA_P_   ' P  '
#define _STR_PSF_ATOM_RNA_B_   ' B  '
#define _STR_PSF_ATOM_RNA_S_   ' S  '
#define _STR_PSF_ATOM_PRO_     ' C  '

! #################
! ###  .ts      ###
! ################# included by 'write_tseries.F90'
! NOTE:  XXXXX_T_ means title string
!        Total width of XXXX_T_ should be same as corresponding XXXX
#define _FMT_TS_INI_TOTAL_     '(f15.3)'
#define _FMT_TS_STEP_          '(1xi12)'
#define _FMT_TS_STEP_T_        '(1xa12)'
#define _FMT_TS_TEMP_          '(1xf8.2)'
#define _FMT_TS_TEMP_T_        '(1xa8)'
#define _FMT_TS_REPLICA_       '(1xi5)'
#define _FMT_TS_REPLICA_T_     '(1xa5)'
#define _FMT_TS_RG_            '(1xf8.2)'
#define _FMT_TS_RG_T_          '(1xa8)'
#define _FMT_TS_RMSD_            '(1xf8.2)'
#define _FMT_TS_RMSD_T_          '(1xa8)'
!#define _FMT_TS_TOTAL_         '(1xf60.50)'
#define _FMT_TS_TOTAL_         '(1xf10.2)'
#define _FMT_TS_TOTAL_T_       '(1xa10)'
#define _FMT_TS_VELO_          '(1xf10.2)'
#define _FMT_TS_VELO_T_        '(1xa10)'
#define _FMT_TS_QSCORE_        '(1xf6.3)'
#define _FMT_TS_QSCORE_T_      '(1xa6)'
#define _FMT_TS_MGO_KAI_       '(1xf6.3)'
#define _FMT_TS_MGO_KAI_T_     '(1xa3, a1, a1, a1)'
#define _FMT_TS_MGO_COEF_      '(1xf6.3)'
#define _FMT_TS_MGO_COEF_T_    '(1xa5, a1)'
#define _FMT_TS_MGO_Q_         '(1xf6.3)'
#define _FMT_TS_MGO_Q_T_       '(1xa5, a1)'
#define _FMT_TS_MGO_STATE_     '(1xf10.2)'
#define _FMT_TS_MGO_STATE_T_   '(1xa9, a1)'
#define _FMT_TS_LOCAL_         '(1xf10.2)'
#define _FMT_TS_LOCAL_T_       '(1xa10)'
#define _FMT_TS_GO_            '(1xf10.2)'
#define _FMT_TS_GO_T_          '(1xa10)'
#define _FMT_TS_MORSE_         '(1xf10.2)'
#define _FMT_TS_MORSE_T_       '(1xa10)'
#define _FMT_TS_REPUL_         '(1xf10.2)'
#define _FMT_TS_REPUL_T_       '(1xa10)'
#define _FMT_TS_WCAATT_         '(1xf10.2)'
#define _FMT_TS_WCAATT_T_       '(1xa10)'
#define _FMT_TS_WCAREP_         '(1xf10.2)'
#define _FMT_TS_WCAREP_T_       '(1xa10)'
#define _FMT_TS_STACK_         '(1xf10.2)'
#define _FMT_TS_STACK_T_       '(1xa10)'
#define _FMT_TS_BASE_          '(1xf10.2)'
#define _FMT_TS_BASE_T_        '(1xa10)'
#define _FMT_TS_HBOND_         '(1xf10.2)'
#define _FMT_TS_HBOND_T_       '(1xa10)'
#define _FMT_TS_ELECT_         '(1xf10.2)'
#define _FMT_TS_ELECT_T_       '(1xa10)'
#define _FMT_TS_HPENE_         '(1xf10.2)'
#define _FMT_TS_HPENE_T_       '(1xa10)'
#define _FMT_TS_INT_           '(1xf10.2)'
#define _FMT_TS_INT_T_         '(1xa10)'
#define _FMT_TS_BOX_           '(1xf10.2)'
#define _FMT_TS_CAP_           '(1xf10.2)'
#define _FMT_TS_BOX_T_         '(1xa10)'
#define _FMT_TS_CAP_T_         '(1xa10)'
#define _FMT_TS_BRIDGE_        '(1xf10.2)'
#define _FMT_TS_BRIDGE_T_      '(1xa10)'
#define _FMT_TS_PULLING_       '(1xf10.2)'
#define _FMT_TS_PULLING_T_     '(1xa10)'
#define _FMT_TS_ANCHOR_        '(1xf10.2)'
#define _FMT_TS_ANCHOR_T_      '(1xa10)'
#define _FMT_TS_REST1D_        '(1xf10.2)'
#define _FMT_TS_REST1D_T_      '(1xa10)'
#define _FMT_TS_IMPLIG_        '(1xf10.5)'
#define _FMT_TS_IMPLIG_T_      '(1xa10)'
#define _FMT_TS_WINDOW_        '(1xf10.2)'
#define _FMT_TS_WINDOW_T_      '(1xa10)'
#define _FMT_TS_CYLINDER_      '(1xf10.2)'
#define _FMT_TS_CYLINDER_T_    '(1xa10)'
