!write_version
!> @brief Outputs version information.

subroutine write_version( lunout )

   implicit none

   integer, intent(in) :: lunout
   
   ! ##############################################
   ! These are supposed to be assigned in Makefile.
#ifdef VERMAJOR
   integer, parameter :: VERSION_MAJOR = VERMAJOR
#else
   integer, parameter :: VERSION_MAJOR = 2
#endif
#ifdef VERMINOR
   integer, parameter :: VERSION_MINOR = VERMINOR
#else
   integer, parameter :: VERSION_MINOR = 1
#endif
#ifdef VERBUILD
   integer, parameter :: VERSION_BUILD = VERBUILD  
#else
   integer, parameter :: VERSION_BUILD = 0
#endif
   ! ##############################################

   write(lunout, '(a)',    ADVANCE='no') '# Generated by CafeMol '
   write(lunout, '(i1)',   ADVANCE='no') VERSION_MAJOR
   write(lunout, '(1a)',   ADVANCE='no') '.'
   write(lunout, '(i0.2)', ADVANCE='no') VERSION_MINOR
   write(lunout, '(1a)',   ADVANCE='no') '.'
   write(lunout, '(i0.4)'              ) VERSION_BUILD

endsubroutine write_version
